version: '3.9'
services:
  redis:
    image: redis:7.0.4-alpine
    container_name: ectapi-cache
    ports:
      - 6379:6379

  db:
    image: postgres:14.5
    restart: always
    container_name: ectapi-db
    # command: postgres -c 'max_connections=300' -c 'shared_buffers=2GB'
    ports:
      - 5433:5432
    environment:
      TZ: Asia/Bangkok
      PGTZ: Asia/Bangkok
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: S3cretp@ssw0rd
      POSTGRES_DB: ectapi
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./config/pg/sql/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      
volumes:
  pg_data: